const router = require('express').Router();
const { body, param } = require('express-validator');
const { authenticate } = require('../middleware/authMiddleware');
const { authorizeRoles } = require('../middleware/roleMiddleware');
const controller = require('../controllers/contractController');
const roles = ['admin', 'hr_manager', 'payroll_user', 'payroll_manager'];
router.use(authenticate, authorizeRoles(...roles));
router.get('/', controller.listContracts);
router.get('/:id', [param('id').isMongoId()], controller.getContract);
router.post('/:id/renew', authorizeRoles('admin', 'payroll_manager'), [param('id').isMongoId(), body('startDate').isISO8601(), body('endDate').optional({ nullable: true }).isISO8601(), body('revisionReason').optional().trim().isLength({ max: 300 })], controller.renewContract);
router.put('/:id', authorizeRoles('admin', 'payroll_manager'), [param('id').isMongoId(), body('basicSalary').optional().isFloat({ min: 0 }), body('overtimeRate').optional().isFloat({ min: 0 }), body('workStartTime').optional().matches(/^([01]\d|2[0-3]):[0-5]\d$/), body('workEndTime').optional().matches(/^([01]\d|2[0-3]):[0-5]\d$/), body('breakMinutes').optional().isInt({ min: 0, max: 480 }), body('position').optional().trim().isLength({ max: 100 }), body('startDate').optional().isISO8601(), body('endDate').optional({ nullable: true }).isISO8601(), body('revisionReason').optional().trim().isLength({ max: 300 }), body('allowances').optional().isArray(), body('allowances.*.name').optional().trim().isLength({ min: 1, max: 80 }), body('allowances.*.amount').optional().isFloat({ min: 0 }), body('deductions').optional().isArray(), body('deductions.*.name').optional().trim().isLength({ min: 1, max: 80 }), body('deductions.*.amount').optional().isFloat({ min: 0 }), body('adjustments').optional().isArray(), body('adjustments.*.name').optional().trim().isLength({ min: 1, max: 80 }), body('adjustments.*.type').optional().isIn(['addition', 'deduction']), body('adjustments.*.amount').optional().isFloat({ min: 0 }), body('adjustments.*.effectiveMonth').optional().matches(/^\d{4}-(0[1-9]|1[0-2])$/), body('adjustments.*.note').optional().trim().isLength({ max: 300 }), body('status').optional().isIn(['draft', 'active', 'expired', 'terminated'])], controller.updateContract);
module.exports = router;
