const router = require('express').Router();
const { body } = require('express-validator');
const { authenticate } = require('../middleware/authMiddleware');
const controller = require('../controllers/selfServiceController');
router.use(authenticate);
router.get('/dashboard', controller.dashboard);
router.get('/time-off/mine', controller.myTimeOff);
router.post('/time-off/mine', [body('timeOffTypeId').isMongoId(), body('startDate').isISO8601(), body('endDate').isISO8601(), body('reason').optional().isLength({ max: 500 })], controller.requestTimeOff);
router.put('/time-off/mine/:id/cancel', controller.cancelMyTimeOff);
router.get('/time-off', require('../middleware/roleMiddleware').authorizeRoles('admin', 'hr_manager', 'payroll_user', 'payroll_manager'), controller.listTimeOff);
router.put('/time-off/:id/approve', require('../middleware/roleMiddleware').authorizeRoles('admin', 'hr_manager'), controller.approveTimeOff);
router.put('/time-off/:id/reject', require('../middleware/roleMiddleware').authorizeRoles('admin', 'hr_manager'), [body('reason').optional().isLength({ max: 500 })], controller.rejectTimeOff);
router.get('/payslips/mine', controller.myPayslips);
router.get('/my-contract', controller.myContract);
module.exports = router;
