import { useEffect, useState } from 'react'
import { Clock3, Users } from 'lucide-react'
import api from '../../services/api'
import { formatDate } from '../../utils/helpers'

export default function AttendanceList() {
  const [items, setItems] = useState([]); const [error, setError] = useState('')
  useEffect(() => { api.get('/attendance').then((r) => setItems(r.data.data.attendance || [])).catch((e) => setError(e.response?.data?.message || 'Could not load attendance')) }, [])
  return <div className="space-y-6"><div><h1 className="text-2xl font-bold text-slate-900">Attendance</h1><p className="mt-1 text-sm text-slate-500">Live work sessions, daily hours, and overtime for all employees.</p></div>{error && <p className="rounded-xl bg-red-50 p-4 text-sm text-red-700">{error}</p>}<div className="overflow-x-auto rounded-2xl border border-slate-200 bg-white shadow-sm"><table className="min-w-full divide-y divide-slate-100"><thead className="bg-slate-50 text-left text-xs font-semibold uppercase text-slate-500"><tr><th className="px-6 py-3">Employee</th><th className="px-6 py-3">Date</th><th className="px-6 py-3">Sessions</th><th className="px-6 py-3">Worked</th><th className="px-6 py-3">Overtime</th><th className="px-6 py-3">Benefit</th></tr></thead><tbody className="divide-y divide-slate-100">{items.map((item) => <tr key={item._id}><td className="px-6 py-4"><p className="font-semibold text-slate-900">{item.userId?.name}</p><p className="text-xs text-slate-500">{item.userId?.employeeCode}</p></td><td className="px-6 py-4 text-sm text-slate-600">{formatDate(item.date)}</td><td className="px-6 py-4 text-sm text-slate-600">{item.sessions?.length || 0}</td><td className="px-6 py-4 text-sm font-semibold text-slate-800">{item.workedHours || 0} hrs</td><td className="px-6 py-4 text-sm font-semibold text-amber-700">{item.overtimeHours || 0} hrs</td><td className="px-6 py-4 text-sm text-slate-600">{item.overtimeChoice === 'cash' ? 'Cash' : item.overtimeChoice === 'comp_time' ? 'Comp time' : '—'}</td></tr>)}</tbody></table>{!items.length && <div className="p-12 text-center text-sm text-slate-500"><Users className="mx-auto mb-3 h-7 w-7 text-slate-300" />No attendance records found.</div>}</div><p className="flex items-center gap-2 text-xs text-slate-500"><Clock3 className="h-4 w-4" />Overnight sessions are split on the server at midnight before daily overtime is calculated.</p></div>
}
