const TimeOffRequest = require('../models/TimeOffRequest');
const TimeOffType = require('../models/TimeOffType');
const TimeOffAllocation = require('../models/TimeOffAllocation');
const Payslip = require('../models/Payslip');
const Attendance = require('../models/Attendance');
const Payrun = require('../models/Payrun');
const User = require('../models/User');
const Contract = require('../models/Contract');
const { getCurrentContract } = require('../services/contractService');

exports.myTimeOff = async (req, res, next) => { try { const [requests, allocations, types] = await Promise.all([TimeOffRequest.find({ userId: req.user._id }).populate('timeOffTypeId', 'name code').sort({ startDate: -1 }), TimeOffAllocation.find({ userId: req.user._id }).populate('timeOffTypeId', 'name code'), TimeOffType.find({ isActive: true })]); res.json({ success: true, data: { requests, allocations, types } }); } catch (error) { next(error); } };
exports.requestTimeOff = async (req, res, next) => { try { const { timeOffTypeId, startDate, endDate, reason } = req.body; const start = new Date(startDate); const end = new Date(endDate); if (end < start) return res.status(400).json({ success: false, message: 'End date cannot be before start date' }); const type = await TimeOffType.findById(timeOffTypeId); if (!type?.isActive) return res.status(400).json({ success: false, message: 'Select an active time-off type' }); const days = Math.floor((end - start) / 86400000) + 1; if (type.allocationRequired) { const allocation = await TimeOffAllocation.findOne({ userId: req.user._id, timeOffTypeId, year: start.getFullYear() }); if (!allocation || allocation.remainingDays < days) return res.status(400).json({ success: false, message: 'Insufficient leave balance for this request' }); } const request = await TimeOffRequest.create({ userId: req.user._id, timeOffTypeId, startDate: start, endDate: end, days, reason }); if (!type.requiresApproval) await approve(request, req.user._id); res.status(201).json({ success: true, data: { request } }); } catch (error) { next(error); } };
exports.listTimeOff = async (_req, res, next) => { try { const requests = await TimeOffRequest.find().populate('userId', 'name employeeCode').populate('timeOffTypeId', 'name code isPaid').sort({ createdAt: -1 }).lean(); res.json({ success: true, data: { requests } }); } catch (error) { next(error); } };
async function approve(request, approver) { const type = await TimeOffType.findById(request.timeOffTypeId); if (type?.allocationRequired) { const allocation = await TimeOffAllocation.findOne({ userId: request.userId, timeOffTypeId: request.timeOffTypeId, year: new Date(request.startDate).getFullYear() }); if (!allocation || allocation.remainingDays < request.days) throw Object.assign(new Error('Insufficient leave balance to approve this request'), { statusCode: 400 }); allocation.usedDays += request.days; allocation.remainingDays -= request.days; await allocation.save(); } request.status = 'approved'; request.approvedBy = approver; request.approvedAt = new Date(); await request.save(); return request; }
exports.approveTimeOff = async (req, res, next) => { try { const request = await TimeOffRequest.findById(req.params.id); if (!request) return res.status(404).json({ success: false, message: 'Leave request not found' }); if (request.status !== 'pending') return res.status(400).json({ success: false, message: 'Only pending requests can be approved' }); res.json({ success: true, data: { request: await approve(request, req.user._id) } }); } catch (error) { next(error); } };
exports.rejectTimeOff = async (req, res, next) => { try { const request = await TimeOffRequest.findById(req.params.id); if (!request) return res.status(404).json({ success: false, message: 'Leave request not found' }); if (request.status !== 'pending') return res.status(400).json({ success: false, message: 'Only pending requests can be rejected' }); request.status = 'rejected'; request.rejectedBy = req.user._id; request.rejectedAt = new Date(); request.rejectionReason = req.body.reason || ''; await request.save(); res.json({ success: true, data: { request } }); } catch (error) { next(error); } };
exports.cancelMyTimeOff = async (req, res, next) => { try { const request = await TimeOffRequest.findOne({ _id: req.params.id, userId: req.user._id }); if (!request) return res.status(404).json({ success: false, message: 'Leave request not found' }); if (request.status !== 'pending') return res.status(400).json({ success: false, message: 'Only pending requests can be cancelled' }); request.status = 'cancelled'; await request.save(); res.json({ success: true, data: { request } }); } catch (error) { next(error); } };
exports.myPayslips = async (req, res, next) => { try { const slips = await Payslip.find({ userId: req.user._id }).sort({ periodEnd: -1 }).lean(); res.json({ success: true, data: { payslips: slips } }); } catch (error) { next(error); } };
exports.myContract = async (req, res, next) => { try { const contract = await getCurrentContract(req.user._id); const expired = !contract || contract.status === 'expired' || contract.status === 'terminated' || (contract.endDate && new Date(contract.endDate) < new Date()); res.json({ success: true, data: { contract, expired } }); } catch (error) { next(error); } };
exports.dashboard = async (req, res, next) => { try { if (req.user.role === 'employee') { const start = new Date(); start.setHours(0, 0, 0, 0); const [today, latestSlip, pending, contract] = await Promise.all([Attendance.findOne({ userId: req.user._id, date: start }).lean(), Payslip.findOne({ userId: req.user._id }).sort({ periodEnd: -1 }).lean(), TimeOffRequest.countDocuments({ userId: req.user._id, status: 'pending' }), getCurrentContract(req.user._id)]); const contractExpired = !contract || contract.status === 'expired' || contract.status === 'terminated' || (contract.endDate && new Date(contract.endDate) < new Date()); return res.json({ success: true, data: { type: 'employee', today: { workedHours: today?.workedHours || 0, overtimeHours: today?.overtimeHours || 0, dailyEarnings: latestSlip?.workedDays ? Number((latestSlip.netSalary / latestSlip.workedDays).toFixed(2)) : 0 }, latestPayslip: latestSlip, pendingLeave: pending, contract: contract ? { _id: contract._id, contractNumber: contract.contractNumber, status: contract.status, startDate: contract.startDate, endDate: contract.endDate, pay: contract.pay } : null, contractExpired } }); }
    const [employees, contracts, payrun, attendanceToday] = await Promise.all([User.countDocuments({ role: 'employee', employmentStatus: 'active' }), Contract.countDocuments({ status: 'active' }), Payrun.findOne().sort({ periodEnd: -1 }).lean(), Attendance.countDocuments({ date: { $gte: new Date(new Date().setHours(0, 0, 0, 0)) }, status: 'present' })]); res.json({ success: true, data: { type: 'management', employees, activeContracts: contracts, attendanceToday, payrun } }); } catch (error) { next(error); } };
