const TimeOffRequest = require('../models/TimeOffRequest');
const TimeOffType = require('../models/TimeOffType');
const TimeOffAllocation = require('../models/TimeOffAllocation');
const Payslip = require('../models/Payslip');
const Attendance = require('../models/Attendance');
const Payrun = require('../models/Payrun');
const User = require('../models/User');
const Contract = require('../models/Contract');
const { getCurrentContract } = require('../services/contractService');

exports.myTimeOff = async (req, res, next) => { try { const [requests, allocations, types] = await Promise.all([TimeOffRequest.find({ userId: req.user._id }).populate('timeOffTypeId', 'name code').sort({ startDate: -1 }), TimeOffAllocation.find({ userId: req.user._id }).populate('timeOffTypeId', 'name code'), TimeOffType.find({ isActive: true })]); res.json({ success: true, data: { requests, allocations, types } }); } catch (error) { next(error); } };
exports.requestTimeOff = async (req, res, next) => { try { const { timeOffTypeId, startDate, endDate, reason } = req.body; const days = Math.max(1, Math.floor((new Date(endDate) - new Date(startDate)) / 86400000) + 1); const request = await TimeOffRequest.create({ userId: req.user._id, timeOffTypeId, startDate, endDate, days, reason }); res.status(201).json({ success: true, data: { request } }); } catch (error) { next(error); } };
exports.listTimeOff = async (_req, res, next) => { try { const requests = await TimeOffRequest.find().populate('userId', 'name employeeCode').populate('timeOffTypeId', 'name code isPaid').sort({ createdAt: -1 }).lean(); res.json({ success: true, data: { requests } }); } catch (error) { next(error); } };
exports.approveTimeOff = async (req, res, next) => { try { const request = await TimeOffRequest.findById(req.params.id); if (!request) return res.status(404).json({ success: false, message: 'Leave request not found' }); if (request.status !== 'pending') return res.status(400).json({ success: false, message: 'Only pending requests can be approved' }); request.status = 'approved'; request.approvedBy = req.user._id; request.approvedAt = new Date(); await request.save(); res.json({ success: true, data: { request } }); } catch (error) { next(error); } };
exports.myPayslips = async (req, res, next) => { try { const slips = await Payslip.find({ userId: req.user._id }).sort({ periodEnd: -1 }).lean(); res.json({ success: true, data: { payslips: slips } }); } catch (error) { next(error); } };
exports.myContract = async (req, res, next) => { try { const contract = await getCurrentContract(req.user._id); const expired = !contract || contract.status === 'expired' || contract.status === 'terminated' || (contract.endDate && new Date(contract.endDate) < new Date()); res.json({ success: true, data: { contract, expired } }); } catch (error) { next(error); } };
exports.dashboard = async (req, res, next) => { try { if (req.user.role === 'employee') { const start = new Date(); start.setHours(0, 0, 0, 0); const [today, latestSlip, pending, contract] = await Promise.all([Attendance.findOne({ userId: req.user._id, date: start }).lean(), Payslip.findOne({ userId: req.user._id }).sort({ periodEnd: -1 }).lean(), TimeOffRequest.countDocuments({ userId: req.user._id, status: 'pending' }), getCurrentContract(req.user._id)]); const contractExpired = !contract || contract.status === 'expired' || contract.status === 'terminated' || (contract.endDate && new Date(contract.endDate) < new Date()); return res.json({ success: true, data: { type: 'employee', today: { workedHours: today?.workedHours || 0, overtimeHours: today?.overtimeHours || 0, dailyEarnings: latestSlip?.workedDays ? Number((latestSlip.netSalary / latestSlip.workedDays).toFixed(2)) : 0 }, latestPayslip: latestSlip, pendingLeave: pending, contract: contract ? { _id: contract._id, contractNumber: contract.contractNumber, status: contract.status, startDate: contract.startDate, endDate: contract.endDate, pay: contract.pay } : null, contractExpired } }); }
    const [employees, contracts, payrun, attendanceToday] = await Promise.all([User.countDocuments({ role: 'employee', employmentStatus: 'active' }), Contract.countDocuments({ status: 'active' }), Payrun.findOne().sort({ periodEnd: -1 }).lean(), Attendance.countDocuments({ date: { $gte: new Date(new Date().setHours(0, 0, 0, 0)) }, status: 'present' })]); res.json({ success: true, data: { type: 'management', employees, activeContracts: contracts, attendanceToday, payrun } }); } catch (error) { next(error); } };
